# name: Deploy to Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to server via SSH
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_KEY }}
#           port: ${{ secrets.SSH_PORT || 22 }}
#           script: |
#             cd ${{ secrets.PROJECT_PATH }}
#             git pull origin main
#             npm install
#             npm run build
#             pm2 restart classroom-front || pm2 start npm --name "classroom-front" -- start
